apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sidecar-security-data
  name: sidecar-security-data
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sidecar-security-data
  template:
    metadata:
      labels:
        app: sidecar-security-data
    spec:
      containers:
      - image: bikertales/sidecar-security-data:5f88150019563304db7517feb8c328fd24361185
        name: sidecar-security-data
        imagePullPolicy: IfNotPresent 
        readinessProbe:
          exec:
            command: 
            - /app/bin/grpc-health-probe
            - -addr=:50051
          initialDelaySeconds: 5
          periodSeconds: 15
        livenessProbe:
          exec:
            command: 
            - /app/bin/grpc-health-probe
            - -addr=:50051
          initialDelaySeconds: 15
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sidecar-security-data
  name: sidecar-security-data
spec:
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
    name: grpc-sidecar-security-data
  selector:
    app: sidecar-security-data 
